const API=window.EMS_CONFIG.API_URL;
const ROLE=window.EMS_CONFIG.ROLE||"guest";
const ADMIN_TOKEN=window.EMS_CONFIG.ADMIN_TOKEN||"";
const state={instruments:[],cars:[],pairings:[],calibrations:[],repairs:[],category:"全部"};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const isAdmin=()=>ROLE==="admin";
function escapeHtml(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function value(obj,keys){for(const k of keys)if(obj&&obj[k]!==undefined&&obj[k]!=="")return obj[k];return""}
function normalizeCategory(raw){const s=String(raw||"").trim();if(/空品車|監測車/.test(s))return"空品車";if(/小孔|孔口/.test(s))return"小孔";if(/高量|採集器|P\d+/i.test(s))return"高量採集器";if(/流量計|浮子|氣體流量/.test(s))return"流量計";if(/PM.?10/i.test(s))return"PM10";return"其他儀器"}
function pill(status){const s=status||"未設定";const cls=/送修|故障|停用|過期/.test(s)?"danger":/校正|保養|部分|待/.test(s)?"warn":/可使用|使用中|正常/.test(s)?"":"neutral";return`<span class="status-pill ${cls}">${escapeHtml(s)}</span>`}
async function fetchAction(action){const r=await fetch(`${API}?action=${encodeURIComponent(action)}&_=${Date.now()}`);if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();if(!j.success)throw new Error(j.message||"API 回傳失敗");return j.data||[]}
async function postAction(action,payload){const r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,adminToken:ADMIN_TOKEN,payload})});const j=await r.json();if(!j.success)throw new Error(j.message||"寫入失敗");return j.data}
function flash(msg,type="success"){const box=$(type==="success"?"#successBox":"#errorBox");box.textContent=msg;box.classList.remove("hidden");setTimeout(()=>box.classList.add("hidden"),4000)}
async function loadAll(){$("#loading").classList.remove("hidden");try{const[ping,instruments,cars,pairings,calibrations,repairs]=await Promise.all([fetchAction("ping"),fetchAction("instruments"),fetchAction("cars"),fetchAction("currentPairings"),fetchAction("orificeCalibrations"),fetchAction("repairs")]);Object.assign(state,{instruments,cars,pairings,calibrations,repairs});$("#apiDot").className="status-dot online";$("#apiStatus").textContent="API 已連線";renderAll()}catch(err){$("#apiDot").className="status-dot offline";$("#apiStatus").textContent="API 連線失敗";flash(`讀取失敗：${err.message}`,"error")}finally{$("#loading").classList.add("hidden")}}
function renderAll(){const active=state.instruments.filter(x=>value(x,["狀態"])!=="停用");$("#metricCars").textContent=state.cars.length;$("#metricOrifices").textContent=active.filter(x=>normalizeCategory(value(x,["類別","名稱"]))==="小孔").length;$("#metricHighVolume").textContent=active.filter(x=>normalizeCategory(value(x,["類別","名稱","編號"]))==="高量採集器").length;$("#metricRepairs").textContent=state.repairs.filter(x=>!/已取回|維修完成|取消/.test(value(x,["狀態"]))).length;renderDashboard();renderCars();renderCategoryTabs();renderInstruments();renderPairingOptions();renderPairings();renderCalibrations();renderRepairs()}
function renderDashboard(){$("#dashboardPairings").innerHTML=state.pairings.slice(0,7).map(x=>`<div class="list-row"><div><strong>${escapeHtml(value(x,["小孔編號"]))}</strong><br><span>${escapeHtml(value(x,["對象編號"])||"倉庫")}</span></div>${pill(value(x,["目前狀態"]))}</div>`).join("")||'<div class="empty">尚無配對資料</div>';$("#dashboardCars").innerHTML=state.cars.map(x=>`<div class="list-row"><div><strong>${escapeHtml(value(x,["車號"]))}</strong><br><span>${escapeHtml(value(x,["目前操作者"])||"尚未指定")}</span></div>${pill(value(x,["車輛狀態"]))}</div>`).join("")||'<div class="empty">尚無空品車資料</div>'}
function renderCars(){const q=$("#carSearch").value.trim().toLowerCase();const rows=state.cars.filter(x=>JSON.stringify(x).toLowerCase().includes(q));$("#carsGrid").innerHTML=rows.map(x=>`<article class="entity-card"><div style="display:flex;justify-content:space-between;gap:12px"><div><h3>${escapeHtml(value(x,["車號"]))} 車</h3><div class="sub">空氣品質監測車</div></div>${pill(value(x,["車輛狀態"]))}</div><dl><dt>目前操作者</dt><dd>${escapeHtml(value(x,["目前操作者"])||"尚未指定")}</dd><dt>借用小孔</dt><dd>${escapeHtml(value(x,["目前借用小孔","目前小孔"])||"無")}</dd><dt>最後更新者</dt><dd>${escapeHtml(value(x,["最後更新者"])||"—")}</dd></dl></article>`).join("")||'<div class="empty">沒有符合的空品車</div>'}
function renderCategoryTabs(){const cats=["全部","小孔","流量計","高量採集器","PM10","其他儀器"];$("#categoryTabs").innerHTML=cats.map(c=>`<button class="category-tab ${state.category===c?"active":""}" data-category="${c}">${c}<span> (${c==="全部"?state.instruments.length:state.instruments.filter(x=>normalizeCategory(value(x,["類別","名稱","編號"]))===c).length})</span></button>`).join("");$$("[data-category]").forEach(b=>b.onclick=()=>{state.category=b.dataset.category;renderCategoryTabs();renderInstruments()})}
function renderInstruments(){const q=$("#instrumentSearch").value.trim().toLowerCase(),status=$("#instrumentStatus").value;const rows=state.instruments.filter(x=>(state.category==="全部"||normalizeCategory(value(x,["類別","名稱","編號"]))===state.category)&&(!status||value(x,["狀態"])===status)&&JSON.stringify(x).toLowerCase().includes(q));$("#instrumentTableBody").innerHTML=rows.map(x=>{const code=value(x,["編號"]);return`<tr><td><strong>${escapeHtml(code)}</strong></td><td>${escapeHtml(normalizeCategory(value(x,["類別","名稱","編號"])))}</td><td>${escapeHtml(value(x,["名稱"]))}</td><td>${escapeHtml([value(x,["品牌"]),value(x,["型號"])].filter(Boolean).join(" / "))}</td><td>${escapeHtml(value(x,["序號"]))}</td><td>${escapeHtml(value(x,["目前位置"])||"倉庫")}</td><td>${pill(value(x,["狀態"]))}</td><td class="admin-only"><div class="admin-action"><button class="secondary-button" onclick="editStatus('${escapeHtml(code)}')">狀態</button><button class="danger-button" onclick="archiveInstrument('${escapeHtml(code)}')">停用</button></div></td></tr>`}).join("")||`<tr><td colspan="8" class="empty">沒有符合的儀器</td></tr>`}
function getOrifices(){return state.instruments.filter(x=>normalizeCategory(value(x,["類別","名稱","編號"]))==="小孔"&&value(x,["狀態"])!=="停用")}
function getHighVolume(){return state.instruments.filter(x=>normalizeCategory(value(x,["類別","名稱","編號"]))==="高量採集器"&&value(x,["狀態"])!=="停用")}
function renderPairingOptions(){$("#pairOrifice").innerHTML=getOrifices().map(x=>`<option value="${escapeHtml(value(x,["編號"]))}">${escapeHtml(value(x,["編號"]))}</option>`).join("");renderTargetOptions()}
function renderTargetOptions(){const type=$("#pairTargetType").value;$("#pairTargetWrap").classList.toggle("hidden",type==="倉庫");let list=type==="空品車"?state.cars:type==="高量採集器"?getHighVolume():[];$("#pairTarget").innerHTML=list.map(x=>{const id=value(x,type==="空品車"?["車號"]:["編號"]);return`<option value="${escapeHtml(id)}">${escapeHtml(id)}</option>`}).join("")}
function renderPairings(){$("#pairingGrid").innerHTML=state.pairings.map(x=>`<article class="entity-card"><div style="display:flex;justify-content:space-between;gap:12px"><div><h3>${escapeHtml(value(x,["小孔編號"]))}</h3><div class="sub">${escapeHtml(value(x,["用途"])||"尚未設定用途")}</div></div>${pill(value(x,["目前狀態"]))}</div><dl><dt>配對類型</dt><dd>${escapeHtml(value(x,["對象類型"])||"—")}</dd><dt>目前位置</dt><dd>${escapeHtml(value(x,["對象編號"])||"倉庫")}</dd><dt>更新者</dt><dd>${escapeHtml(value(x,["最後更新者"])||"—")}</dd></dl></article>`).join("")||'<div class="empty">尚無目前配對資料</div>'}
function renderCalibrations(){$("#calibrationTableBody").innerHTML=state.calibrations.map(x=>`<tr><td><strong>${escapeHtml(value(x,["小孔編號"]))}</strong></td><td>${escapeHtml(value(x,["報告編號"]))}</td><td>${escapeHtml(value(x,["校正日期"]))}</td><td>${escapeHtml(value(x,["到期日"]))}</td><td>${escapeHtml(value(x,["斜率(m³/min)"]))}</td><td>${escapeHtml(value(x,["截距(m³/min)"]))}</td><td>${escapeHtml(value(x,["相關係數(m³/min)"]))}</td><td>${escapeHtml(value(x,["保存形式"])||"紙本")}</td></tr>`).join("")||'<tr><td colspan="8" class="empty">尚無小孔校正資料</td></tr>'}
function renderRepairs(){$("#repairTableBody").innerHTML=state.repairs.map(x=>`<tr><td>${escapeHtml(value(x,["對象類型"]))}</td><td>${escapeHtml(value(x,["所屬空品車"])||"—")}</td><td><strong>${escapeHtml(value(x,["儀器ID/編號","儀器項目"]))}</strong></td><td>${escapeHtml(value(x,["故障內容"]))}</td><td>${escapeHtml(value(x,["送修日期"]))}</td><td>${pill(value(x,["狀態"]))}</td><td>${escapeHtml(value(x,["登記者"])||"—")}</td></tr>`).join("")||'<tr><td colspan="7" class="empty">目前沒有維修紀錄</td></tr>'}
async function archiveInstrument(code){if(!confirm(`確定將 ${code} 設為停用？歷史紀錄會保留。`))return;try{await postAction("archiveInstrument",{編號:code,最後更新者:"良澤"});flash(`${code} 已停用`);await loadAll()}catch(e){flash(e.message,"error")}}
async function editStatus(code){const status=prompt(`${code} 新狀態：可使用／校正中／維修／故障／停用`);if(!status)return;try{await postAction("updateInstrument",{編號:code,狀態:status,最後更新者:"良澤"});flash(`${code} 狀態已更新`);await loadAll()}catch(e){flash(e.message,"error")}}
window.archiveInstrument=archiveInstrument;window.editStatus=editStatus;
function switchView(name){$$(".view").forEach(v=>v.classList.remove("active"));$$(".nav-item").forEach(v=>v.classList.remove("active"));$(`#view-${name}`).classList.add("active");$(`.nav-item[data-view="${name}"]`)?.classList.add("active");const titles={dashboard:["系統總覽","即時讀取 EMS-Air Google 試算表"],cars:["空品車","只有空品車顯示目前操作者"],instruments:["儀器管理","分類、新增與停用"],pairings:["小孔配對","下拉式快速配對與歸還"],calibrations:["小孔校正","紙本報告關鍵資料"],repairs:["維修管理","空品車及各項儀器維修紀錄"]};$("#pageTitle").textContent=titles[name][0];$("#pageSubtitle").textContent=titles[name][1];$("#sidebar").classList.remove("open")}
$$(".nav-item").forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$("[data-go]").forEach(b=>b.onclick=()=>switchView(b.dataset.go));$("#refreshButton").onclick=loadAll;$("#instrumentSearch").oninput=renderInstruments;$("#instrumentStatus").onchange=renderInstruments;$("#carSearch").oninput=renderCars;$("#menuButton").onclick=()=>$("#sidebar").classList.toggle("open");$("#pairTargetType").onchange=renderTargetOptions;
$("#addInstrumentButton").onclick=()=>$("#instrumentModal").classList.remove("hidden");$$("[data-close-modal]").forEach(b=>b.onclick=()=>$("#instrumentModal").classList.add("hidden"));
$("#instrumentForm").onsubmit=async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.target).entries());payload.目前位置=payload.目前位置||"倉庫";payload.最後更新者="良澤";try{await postAction("addInstrument",payload);$("#instrumentModal").classList.add("hidden");e.target.reset();flash(`${payload.編號} 已新增`);await loadAll()}catch(err){flash(err.message,"error")}};
$("#savePairingButton").onclick=async()=>{const type=$("#pairTargetType").value;const payload={小孔編號:$("#pairOrifice").value,對象類型:type,對象編號:type==="倉庫"?"倉庫":$("#pairTarget").value,用途:$("#pairPurpose").value,最後更新者:"良澤"};try{await postAction("savePairing",payload);flash(`${payload.小孔編號} 已配對至 ${payload.對象編號}`);await loadAll()}catch(err){flash(err.message,"error")}};
if(!isAdmin())$$(".admin-only").forEach(el=>el.classList.add("hidden"));
$("#roleLabel").textContent=isAdmin()?"最高管理員":"唯讀使用者";
loadAll();